### ISSUE TITLE
Feedback.html not included in game

### ISSUE THREAD

**Issue by alicerunsonfedora** [TheAngelReturns/the-angel-returns#13]
* Beta version: 0.1.2beta1
* Platform: macOS
* Contact email address: Picugaming@gmail.com

## Description
Feedback.html wasn't included within the game's files, producing a 404 in browser when launching “Send Feedback”

> Note: pulled from #12 as a separate issue

**Comment by alicerunsonfedora** [comment]
I just looked at the compiled binaries and have confirmed that the file is indeed there. Maybe Ren’Py is looking for the file in the game folder?

**Comment by sr229** [comment]
probably, RenPy is cwd'ed on the `game/` folder, reminder.

**Comment by alicerunsonfedora** [comment]
Confirmed that tester forgot to copy over the feedback.html file. As long as we create an instruction file that says to copy over everything that’s included, we should be fine. Case closed.
