### ISSUE TITLE
Get Sayonika in the game

### ISSUE THREAD

**Issue by alicerunsonfedora** [TheAngelReturns/the-angel-returns#16]
It's an absolute necessity. A must!

**Comment by sr229** [comment]
I'll bet this mod will be adding Sayonika in less than 10 days 

if they do I'll be damned cos I'll take 3 shots of tequilla :beers:

**Comment by alicerunsonfedora** [comment]
We have to! She'd make a great assistant/partner for the Angel.

**Comment by alicerunsonfedora** [comment]
Well, her menu sprite is there, as well as the proper screens for her name box and text box. All that's missing now are the sprites and an author to write as Sayonika herself.

![HL3 Menu](https://media.discordapp.net/attachments/457606890617045009/473503060790870017/screenshot0010.png?width=1640&height=923)

Perhaps @sr229 should be in charge of writing as Sayonika?

**Comment by alicerunsonfedora** [comment]
The sprites are in!
