### ISSUE TITLE
Create automated builds with master branch

### ISSUE THREAD

**Issue by alicerunsonfedora** [TheAngelReturns/the-angel-returns#4]

**Comment by sr229** [comment]
Won't be possible: See our [Travis log](https://travis-ci.org/Sayo-nika/quickstart-travis/jobs/395524279#L1) for details.

**Comment by alicerunsonfedora** [comment]
This should be added to the _0.1.2_ update, which will also include a beta version of AliceOS.

**Comment by alicerunsonfedora** [comment]
Alright, #10 just got pushed in, nothing's really changed game-wise. However, template versions have been updated accordingly. I hope this helps you with further testing.

**Comment by sr229** [comment]
Should be possible now with PR #11.

To trigger a build just create a release or push a git tag. Make sure `GITHUB_API_KEY` is set though, like what I said on the PR before.

**Comment by alicerunsonfedora** [comment]
Merged into latest commits
